### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by atherdon** [ammein/database-api#2]
.

**Comment by ammein** [comment]
Hi @atherdon , I'm so excited when I first heard an offer from you. Although , I'm not a real developer on my own occupation. I'm a UIUX Designer with Front-End Master. Also , I'm in love with Javascript and learned NodeJS easily with upcoming React of my todo learning list. And yes, I would like to contribute to your open source projects if your project requires NodeJS language. Moreover , I'm a beginner developer + self taught learner . So be gentle with me , yeah ? Haha 😆 

P/s : We should discuss more on this and you also could find me on linkedIn for more closeup view of my profile [LinkedIn](https://www.linkedin.com/in/amin-shazrin/)
